spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET}
  expiration: 7200
  refresh-duration: 86400
  reset-duration: 3000

feign:
  hystrix:
    enabled: false


server:
  port: 8081

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

google:
  client-web-id: 871727759193-un865a51acfobga2nbua4k1j5p9k1nst.apps.googleusercontent.com
  client-app-id: 871727759193-kfbiudvr73r4lmc9jmgc11jih9or8ur6.apps.googleusercontent.com
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-web-uri: http://localhost:3000/authenticate
  user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

springdoc:
  api-docs:
    enabled: true  # Bật endpoint /v3/api-docs
  swagger-ui:
    enabled: true # Tắt UI nếu muốn

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://your_prod_host:5432/auth_service
    driver-class-name: org.postgresql.Driver
    username: your_prod_username
    password: your_prod_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

google:
  client-id: YOUR_GOOGLE_CLIENT_ID
  client-secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect-uri: http://localhost:3000/authenticate
  token-uri: https://oauth2.googleapis.com/token
  user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo