spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/notification_service?authSource=admin
      database: notification_service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.springframework.data.mongodb.core: info
    org.springframework: info

springdoc:
  api-docs:
    enabled: true  # Bật endpoint /v3/api-docs
  swagger-ui:
    enabled: true # Tắt UI nếu muốn

brevo:
  api_key: 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
server:
  port: 8083

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

---
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://your_prod_username:your_prod_password@your_prod_host:27017/notification_service
      database: notification_service


logging:
  level:
    root: warn
