name: pbl6
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0 # Cập nhật để tương thích với Dart 3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.0.0
  get_it: ^8.2.0
  font_awesome_flutter: ^10.10.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  motion_toast: ^2.14.0
  google_sign_in: ^6.1.5
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  jwt_decode: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image_picker: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.jpg
    - assets/images/recruiter.png
    - assets/images/student.png
    - assets/images/welcome_screen.jpg
    - assets/images/avatar.png
  fonts:
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf
