spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  application:
    name: statistic-service

  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/statistic_service?authSource=admin
      database: statistic_service
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
     time-to-live: 600000 # 600,000 ms = 10 phút (Dữ liệu sẽ được làm mới mỗi 10p)
     cache-null-values: false

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: statistic-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.springframework.data.mongodb.core: info
    org.springframework: info

springdoc:
  api-docs:
    enabled: true  # Bật endpoint /v3/api-docs
  swagger-ui:
    enabled: true # Tắt UI nếu muốn

server:
  port: 8087

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost

---
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: statistic-service

  data:
    mongodb:
      uri: mongodb://your_prod_username:your_prod_password@your_prod_host:27017/statistic_service
      database: statistic_service


logging:
  level:
    root: warn
